<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>Magic_Generator</RootNamespace>
    <TargetFramework>net8.0</TargetFramework>
    <OptionStrict>On</OptionStrict>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <RemoveIntegerChecks>True</RemoveIntegerChecks>
    <DefineDebug>False</DefineDebug>
    <DefineTrace>False</DefineTrace>
    <PlatformTarget>x64</PlatformTarget>
    <OutputPath>bin\Release</OutputPath>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <RemoveIntegerChecks>True</RemoveIntegerChecks>
    <DefineTrace>False</DefineTrace>
    <PlatformTarget>x64</PlatformTarget>
    <OutputPath>bin\Release</OutputPath>
  </PropertyGroup>

</Project>
